jobs:
  autograding:
    name: autograding
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wadefagen/autograding@v1
      with:
        path: mp3/
        test_suite: autograding
  week2:
    name: week2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wadefagen/autograding@v1
      with:
        path: mp3/
        test_suite: week2
name: mp3 autograding
'on':
  push:
    paths: mp3/**
